version: '1.0'

stages:
  - 'clone'
  - 'deployVercel'

steps:
  clone:
    title: 'Cloning repository'
    type: 'git-clone'
    repo: 'corykitchensmotorefi/corykitchens-helloworld'
    revision: 'branch'
    stage: 'clone'

deployVercel:
  stage: 'deployVercel'
  type: 'freestyle'
  image: 'circleci/node:12.19.0'
  working_directory: '${{clone}}'
  commands:
    - 'npx vercel -d -t $VERCEL_TOKEN --prod'
  title: 'Deploy corykitchens-helloworld to Vercel'
  # environment:
  #   - VERCEL_PROJECT_ID=${{VERCEL_PROJECT_ID}}