version: '1.0'

stages:
  - 'clone'
  - 'deployVercel'

steps:
  clone:
    title: 'Cloning repository'
    type: 'git-clone'
    repo: 'corykitchensmotorefi/corykitchens-helloworld'
    revision: 'main'
    stage: 'clone'

  # install:
  #   title: 'Installing dependencies'
  #   type: 'freestyle'
  #   image: 'circleci/node:12.19.0'
  #   working_directory: '${{clone}}'
  #   commands:
  #     - 'npm install'
  #   when:
  #     steps:
  #       - name: clone

  deployVercel:
    stage: 'deployVercel'
    type: 'freestyle'
    image: 'circleci/node:12.19.0'
    working_directory: '${{clone}}'
    commands:
      - 'npm ci'
      - 'npx vercel -d -t $VERCEL_TOKEN --prod'
    title: 'Deploy corykitchens-helloworld to Vercel'
